<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Python_Data_Analytics_Course/blob/main/4_Problems/1_24_Pandas Inspection.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

In [25]:

import pandas as pd
df = pd.read_csv("hf://datasets/lukebarousse/data_jobs/data_jobs.csv")

---

## 🟩 Access Third Row (1.24.1)

In [15]:
df.iloc[3]

job_title_short                                              Data Engineer
job_title                LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...
job_location                                               San Antonio, TX
job_via                                                  via Diversity.com
job_schedule_type                                                Full-time
job_work_from_home                                                   False
search_location                                       Texas, United States
job_posted_date                                        2023-07-04 13:01:41
job_no_degree_mention                                                 True
job_health_insurance                                                 False
job_country                                                  United States
salary_rate                                                            NaN
salary_year_avg                                                        NaN
salary_hour_avg                                                        NaN
company_name                                  Southwest Research Institute
job_skills               ['python', 'c++', 'java', 'matlab', 'aws', 'te...
job_type_skills          {'cloud': ['aws'], 'libraries': ['tensorflow',...
Name: 3, dtype: object

---

## 🟨 Unique Job Countries (1.24.2)

In [16]:
df.job_country.unique()

array(['United States', 'Mexico', 'Germany', 'Sudan', 'Romania',
       'Denmark', 'Switzerland', 'France', 'Brazil', 'United Kingdom',
       'India', 'Poland', 'Belgium', 'Russia', 'Serbia', 'Singapore',
       'Costa Rica', 'Ireland', 'Italy', 'Malaysia', 'Canada', 'Uruguay',
       'Namibia', 'Estonia', 'Israel', 'Hungary', 'Austria',
       'Philippines', 'Egypt', 'Australia', 'Chile', 'Spain',
       'Netherlands', 'South Africa', 'Colombia', 'Hong Kong', 'Kuwait',
       'Finland', 'Luxembourg', 'China', 'Puerto Rico', 'Sweden',
       'Saudi Arabia', 'Argentina', 'Turkey', 'Panama', 'Nigeria',
       'New Zealand', 'Ukraine', 'Jordan', 'United Arab Emirates',
       'Armenia', 'Pakistan', 'Lesotho', 'Mauritius', 'Portugal',
       'Bahrain', 'Taiwan', "Côte d'Ivoire", 'U.S. Virgin Islands',
       'Réunion', 'Kazakhstan', 'Lithuania', 'Moldova', 'Belarus',
       'Cyprus', 'Bulgaria', 'Honduras', 'Czechia', 'Peru', 'South Korea',
       'Malta', 'Indonesia', 'Tunisia', 'Latvia', 'Slovakia', 'Lebanon',
       'Japan', 'Sri Lanka', 'Slovenia', 'Bangladesh', 'Greece',
       'Ecuador', 'Oman', 'Kenya', 'Guyana', 'Vietnam', 'Norway',
       'Senegal', 'El Salvador', 'Iceland', 'Thailand', 'Ghana',
       'Croatia', 'Myanmar', 'Nepal', 'Morocco', 'Guadeloupe', 'Iraq',
       'Palestine', 'Guinea', 'Albania', 'Guatemala', 'Qatar', 'Uganda',
       'Bolivia', nan, 'Dominican Republic', 'Ethiopia', 'Haiti',
       'Uzbekistan', 'Bahamas', 'Liberia', 'Montenegro', 'Cayman Islands',
       'Mongolia', 'Macedonia (FYROM)', 'Azerbaijan', 'Burkina Faso',
       'Guam', 'Trinidad and Tobago', 'Benin', 'Kyrgyzstan',
       'Bosnia and Herzegovina', 'Zambia', 'Cameroon', 'Venezuela',
       'Barbados', 'Togo', 'Rwanda', 'Cambodia', 'Algeria', 'Afghanistan',
       'Congo, Democratic Republic of the', 'Zimbabwe', 'Jamaica',
       'Suriname', 'Mozambique', 'Yemen', 'Tanzania', 'Madagascar',
       'Mali', 'Paraguay', 'Brunei', 'Malawi', 'Nicaragua', 'Libya',
       'Tajikistan', 'Mauritania', 'Botswana', 'Fiji',
       'Northern Mariana Islands', 'Angola', 'Somalia',
       'Papua New Guinea', 'Gambia', 'Djibouti', 'Laos', 'Curaçao',
       'Maldives', 'Bhutan'], dtype=object)

---

## 🟨 Filter by Job Schedule Type and Display (1.24.3)

In [19]:
df.job_schedule_type.unique()

array(['Full-time', 'Contractor and Temp work',
       'Full-time and Internship', 'Temp work', 'Contractor',
       'Full-time and Part-time', 'Full-time and Temp work',
       'Full-time and Contractor', 'Part-time', 'Internship', nan,
       'Part-time and Contractor', 'Temp work and Internship',
       'Full-time, Part-time, and Contractor',
       'Full-time, Part-time, and Internship',
       'Full-time, Contractor, and Temp work',
       'Full-time, Part-time, and Temp work',
       'Full-time, Temp work, and Internship',
       'Full-time, Contractor, and Internship',
       'Part-time and Internship', 'Contractor and Internship',
       'Part-time and Full-time', 'Part-time and Temp work',
       'Full-time and Volunteer', 'Contractor, Temp work, and Internship',
       'Full-time and Per diem', 'Per diem', 'Volunteer',
       'Part-time, Contractor, and Temp work',
       'Full-time, Temp work, and Per diem',
       'Part-time, Temp work, and Internship', 'Contractor and Part-time',
       'Part-time and Per diem', 'Contractor and Per diem',
       'Internship and Full-time', 'Internship and Per diem',
       'Full-time, Part-time, and Volunteer', 'Temp work and Full-time',
       'Part-time, Internship, and Volunteer', 'Part-time and Volunteer',
       'Part-time, Contractor, and Internship',
       'Internship and Volunteer', 'Contractor and Full-time',
       'Full-time, Part-time, and Per diem',
       'Full-time, Contractor, and Volunteer',
       'Temp work, Full-time, and Part-time', 'Pekerjaan tetap',
       'Kontraktor'], dtype=object)

---

## 🟥 Check Missing Values (1.24.4)

In [20]:
df.isna().sum()

job_title_short               0
job_title                     1
job_location               1045
job_via                       8
job_schedule_type         12667
job_work_from_home            0
search_location               0
job_posted_date               0
job_no_degree_mention         0
job_health_insurance          0
job_country                  49
salary_rate              752674
salary_year_avg          763738
salary_hour_avg          775079
company_name                 18
job_skills               117037
job_type_skills          117037
dtype: int64

In [21]:
df.job_posted_date[0]

'2023-06-16 13:44:15'

In [26]:
df['job_posted_date'] = pd.to_datetime(df.job_posted_date)

In [28]:
df['job_posted_month']=df['job_posted_date'].dt.month

In [31]:
df.sort_values(by='job_posted_month', inplace=True)

In [32]:
df.drop(labels='salary_hour_avg', axis=1, inplace=True)

In [33]:
df.dropna(subset=['salary_year_avg'], inplace=True)

---