<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Python_Data_Analytics_Course/blob/main/4_Problems/1_26_Pandas Analysis.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

In [1]:

import pandas as pd
from datasets import load_dataset

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md: 0.00B [00:00, ?B/s]

data_jobs.csv:   0%|          | 0.00/231M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/785741 [00:00<?, ? examples/s]

---

## 🟩 Calculate Mean Salary (1.26.1)

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  object
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), float64(2), object(12)
memory usage: 86.2+ MB

In [5]:
df['salary_year_avg'].mean()

np.float64(123286.27407182401)

---

## 🟩 Calculate Median Salary (1.26.2)

In [6]:
df['salary_year_avg'].median()

115000.0

---

## 🟨 Average Hourly Salary by Job Title (1.26.3)

In [9]:
df.groupby('job_title_short')['salary_hour_avg'].mean().sort_values(ascending=False)

job_title_short
Senior Data Engineer         62.848496
Data Engineer                57.196998
Senior Data Scientist        54.105631
Data Scientist               49.361403
Machine Learning Engineer    48.477935
Senior Data Analyst          47.661218
Software Engineer            46.452019
Cloud Engineer               45.560715
Business Analyst             42.723415
Data Analyst                 38.106918
Name: salary_hour_avg, dtype: float64

---

## 🟨 Job with Lowest Salary (1.26.4)

In [14]:
df.groupby('job_title_short')['salary_year_avg'].min().sort_values(ascending=True).head(1)

job_title_short
Data Engineer    15000.0
Name: salary_year_avg, dtype: float64

---

## 🟨 Job Count by Country (1.26.5)

In [16]:
df.groupby('job_location')['job_title_short'].count().sort_values(ascending=False)

job_location
Anywhere                        69552
Singapore                       23415
Paris, France                   12311
Bengaluru, Karnataka, India     11474
London, UK                      10564
                                ...
Aalsmeerderbrug, Netherlands        1
Aalst, Belgium   (+2 others)        1
Aarhus C, Denmark                   1
Ølstykke, Denmark                   1
Étival-lès-le-Mans, France          1
Name: job_title_short, Length: 17217, dtype: int64

---