<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Python_Data_Analytics_Course/blob/main/4_Problems/2_02_Pandas Data Cleaning.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

In [53]:
# Importing Libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

# Loading Data
df = pd.read_csv("hf://datasets/lukebarousse/data_jobs/data_jobs.csv")

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

## 🟩 Remove Rows with Missing Values (2.2.1)

In [50]:
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,NaN,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,NaN,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,NaN,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,NaN,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,NaN,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 785640 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785640 non-null  object
 1   job_title              785639 non-null  object
 2   job_location           784595 non-null  object
 3   job_via                785632 non-null  object
 4   job_schedule_type      772975 non-null  object
 5   job_work_from_home     785640 non-null  bool
 6   search_location        785640 non-null  object
 7   job_posted_date        785640 non-null  datetime64[ns]
 8   job_no_degree_mention  785640 non-null  bool
 9   job_health_insurance   785640 non-null  bool
 10  job_country            785591 non-null  object
 11  salary_rate            33066 non-null   object
 12  salary_year_avg        22002 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785622 non-null  object
 15  job_skills             668654 non-null  object
 16  job_type_skills        668654 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 92.2+ MB

In [51]:
df = df.dropna()

In [47]:
df.head()

AttributeError: 'function' object has no attribute 'head'

---

## 🟨 Remove Duplicate Rows (2.2.2)

In [54]:
df = df.drop_duplicates()

---

## 🟨 Fill Missing Values in Column (2.2.3)

In [61]:
median_yearly = df.salary_year_avg.median()
median_hourly = df.salary_hour_avg.median()

df['salary_year_avg'] = df.salary_year_avg.fillna(median_yearly)
df['salary_hour_avg'] = df.salary_hour_avg.fillna(median_hourly)
df = df.median_hourly.drop()

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 785640 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785640 non-null  object
 1   job_title              785639 non-null  object
 2   job_location           784595 non-null  object
 3   job_via                785632 non-null  object
 4   job_schedule_type      772975 non-null  object
 5   job_work_from_home     785640 non-null  bool
 6   search_location        785640 non-null  object
 7   job_posted_date        785640 non-null  datetime64[ns]
 8   job_no_degree_mention  785640 non-null  bool
 9   job_health_insurance   785640 non-null  bool
 10  job_country            785591 non-null  object
 11  salary_rate            33066 non-null   object
 12  salary_year_avg        785640 non-null  float64
 13  salary_hour_avg        785640 non-null  float64
 14  company_name           785622 non-null  object
 15  job_skills             668654 non-null  object
 16  job_type_skills        668654 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 92.2+ MB

In [64]:
df = df.drop(columns='median_hourly')

In [74]:
df.plot(x='job_title_short', y='salary_year_avg', kind='bar')

KeyboardInterrupt:

Error in callback <function _draw_all_if_interactive at 0x79de5c0544a0> (for post_execute):

KeyboardInterrupt:

Error in callback <function flush_figures at 0x79de5c1ed9e0> (for post_execute):

KeyboardInterrupt:

In [79]:
df.groupby('job_title_short')['salary_year_avg'].agg(['median', 'mean', 'max', 'min'])

                             median           mean       max      min
job_title_short
Business Analyst           115000.0  114702.574640  387460.0  16500.0
Cloud Engineer             115000.0  114980.330022  280000.0  42000.0
Data Analyst               115000.0  114411.845140  650000.0  25000.0
Data Engineer              115000.0  115365.517566  525000.0  15000.0
Data Scientist             115000.0  115721.547249  960000.0  27000.0
Machine Learning Engineer  115000.0  115481.710775  325000.0  30000.0
Senior Data Analyst        115000.0  114957.854190  425000.0  30000.0
Senior Data Engineer       115000.0  116101.129084  425000.0  35000.0
Senior Data Scientist      115000.0  116792.954544  890000.0  45000.0
Software Engineer          115000.0  114983.300368  375000.0  28000.0

---